### ISSUE TITLE
[EPIC] Cleanup of stac builder code

### ISSUE THREAD

**Issue by VictorVerhaert** [VitoTAP/stac-catalog-builder#53]
This issue serves as an overview of changes to make to the stac builder to clean up the code.
It's goal is to make the builder easier to understand, debug and expand.

- [ ] use pyproject.toml as only dependency source to prevent inconsistent environments (terracatalogue might need a seperate init for this)
- [ ] Use the AssetMetadata as the generic interface for all the data that needs to be extracted out of sources. After this al generic behaviour should be able to be implemented by using custom callbacks. This allows for a lot of code to be removed improving readability. 
- [ ] [optional/discussion needed] move all the arguments to the config file so one workflow could in theory be used for all collections that do not need custom item postprocessors. (This would allow for easily rebuilding all collections should a bug be found in the builder)
- [ ] remove backup code for saving to geoparquet and dataframes as this is not being used for debugging and complicates the code
- [ ] cleanup TODO's (currently 95 in total) -> either create an issue for it and link it in the code, directly fix it or deem the todo unnecessary
- [ ] remove docker functionality (was this ever used?)
- [ ] remove makefile funtionality -> setting up environments should not be the responsibility of the stac builder and should be easy with the pyproject.toml, the makefiles for building collections are not being used or up to date
- [ ] running extra linting tools on the source code (similar to the openeo-python-client)
- [ ] Update the documentation (most of it is outdated)
- [ ] Update the template for new collections -> keep this up to date with new collections being build

**Comment by VictorVerhaert** [comment]
extra: 

- [ ] add uv.lock and docs on how to use this

**Comment by VictorVerhaert** [comment]
- [ ] fix linting + add black in code repo

**Comment by manugv** [comment]
To remove/change
- [ ] Remove stactools as it is unmaintained now. 
     - only used for "ReadHrefModifier" in line 166 stacbuilder/collector.py. Find alternative and change it.
     - This is function to modify hrefs. Is it really needed? Use case?
- [ ] Use one system for s3 if possible 
     - either fsspec (with s3fs) or boto3 for s3 filesystems. 
     - terracatalogue depends on boto3
     - universal_pathlib depends upon fsspec
     - Having multiple versions leads to issues with package dependencies when we use stacbuilder with other packages (for example in weed project)   
-  [ ] remove numpy, shapely and pyproj as they are installed by openeo or/and geopandas. No need to constrain them by separately installing them.
- [ ] Maybe remove requests as it is installed by openEO
- [ ] Remove pyarrow as no parquet files are read. Or make it an optional dependency.

**Comment by VictorVerhaert** [comment]
@manugv for the s3 deps: I explicitly removed the boto3 requirement, but indeed terracataloge still depends on this.
Terracatalogue is now an optional dependency so conflicts should be easier to resolve.
This SO thread contains some tricks on how to install both boto as fsspec and s3fs: https://stackoverflow.com/questions/75743038/resolving-dependencies-fails-on-boto3-and-s3fs-using-poetry

(fix is still on my local branch but documenting progress here to track everything)
